name: KXCSpaceFS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linux-build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-image-generic linux-headers-generic
    - name: Node Cleanup (Carlos Alexandro Becker)
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
    - name: Update Kernel Source
      run: |
        cd /usr/src
        ls
        cd /lib/modules/$(uname -r)
        sudo rm build
        sudo ln -s /usr/src/linux-6* build
    - name: Setup
      run: mkdir build
    - name: Make
      run: make all -f src/Makefile
    - name: Upload mkfs.KXCSpaceFS
      uses: actions/upload-artifact@v4
      with:
        name: mkfs.KXCSpaceFS
        path: /home/runner/work/KXCSpaceFS/KXCSpaceFS/build/mkfs.kxcspacefs
    - name: Upload KXCSpaceFS.ko
      uses: actions/upload-artifact@v4
      with:
        name: KXCSpaceFS.ko
        path: /home/runner/work/KXCSpaceFS/KXCSpaceFS/build/kxcspacefs.ko
