name: KXCSpaceFS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linux-build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: Setup
      run: mkdir build
    - name: Make
      run: make all -f src/Makefile
    - name: Upload mkfs.KXCSpaceFS
      uses: actions/upload-artifact@v4
      with:
        name: mkfs.KXCSpaceFS
        path: /home/runner/work/KXCSpaceFS/KXCSpaceFS/build/mkfs.kxcspacefs
    - name: Upload KXCSpaceFS.ko
      uses: actions/upload-artifact@v4
      with:
        name: KXCSpaceFS.ko
        path: /home/runner/work/KXCSpaceFS/KXCSpaceFS/build/kxcspacefs.ko