name: KXCSpaceFS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linux-build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libelf-dev
    - name: Update Kernel Source
      run: |
        cd /usr/src
        sudo wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.2.tar.xz
        sudo tar xvf linux-*.tar.xz
        sudo rm linux-*.tar.xz
        cd linux-6*
        sudo make oldconfig && sudo make prepare
        cd /lib/modules/$(uname -r)
        sudo rm build
        sudo ln -s /usr/src/linux-6* build
    - name: Setup
      run: mkdir build
    - name: Make
      run: make all -f src/Makefile
